"use strict";

function route({ method, path, pattern, scope, summary, operationId, rewrite = null, idempotent = false }) {
  return Object.freeze({ method, path, pattern, scope, summary, operationId, rewrite, idempotent });
}

const API_V1_ROUTES = Object.freeze([
  route({
    method: "GET",
    path: "/api/v1/account",
    pattern: /^\/api\/v1\/account\/?$/,
    scope: "account:read",
    summary: "현재 Quilo 계정과 크레딧 요약",
    operationId: "getAccount",
  }),
  route({
    method: "GET",
    path: "/api/v1/api-requests",
    pattern: /^\/api\/v1\/api-requests\/?$/,
    scope: "account:read",
    summary: "현재 토큰 사용자의 최근 API 요청 기록",
    operationId: "listApiRequests",
  }),
  route({
    method: "GET",
    path: "/api/v1/jobs",
    pattern: /^\/api\/v1\/jobs\/?$/,
    scope: "jobs:read",
    summary: "최근 작업 목록",
    operationId: "listJobs",
    rewrite: () => "/api/me/jobs",
  }),
  route({
    method: "GET",
    path: "/api/v1/jobs/{id}",
    pattern: /^\/api\/v1\/jobs\/([^/]+)\/?$/,
    scope: "jobs:read",
    summary: "작업 단건 상태와 진행 정보",
    operationId: "getJob",
  }),
  route({
    method: "POST",
    path: "/api/v1/jobs/{id}/abort",
    pattern: /^\/api\/v1\/jobs\/([^/]+)\/abort\/?$/,
    scope: "jobs:write",
    summary: "진행 중인 작업 중단",
    operationId: "abortJob",
    rewrite: (match) => `/api/jobs/${match[1]}/abort`,
  }),
  route({
    method: "POST",
    path: "/api/v1/jobs/{id}/email",
    pattern: /^\/api\/v1\/jobs\/([^/]+)\/email\/?$/,
    scope: "jobs:write",
    summary: "완료 작업의 파일함 링크를 인증 이메일로 1회 전송",
    operationId: "emailJobResult",
    rewrite: (match) => `/api/jobs/${match[1]}/email`,
  }),
  route({
    method: "GET",
    path: "/api/v1/jobs/{id}/events",
    pattern: /^\/api\/v1\/jobs\/([^/]+)\/events\/?$/,
    scope: "jobs:read",
    summary: "작업 진행 SSE 스트림",
    operationId: "streamJobEvents",
    rewrite: (match) => `/api/jobs/${match[1]}/stream`,
  }),
  route({
    method: "GET",
    path: "/api/v1/jobs/{id}/download",
    pattern: /^\/api\/v1\/jobs\/([^/]+)\/download\/?$/,
    scope: "files:read",
    summary: "완료 작업 결과 다운로드",
    operationId: "downloadJob",
    rewrite: (match) => `/api/jobs/${match[1]}/download`,
  }),
  route({
    method: "GET",
    path: "/api/v1/files",
    pattern: /^\/api\/v1\/files\/?$/,
    scope: "files:read",
    summary: "24시간 파일함 목록",
    operationId: "listFiles",
    rewrite: () => "/api/me/files",
  }),
  route({
    method: "GET",
    path: "/api/v1/files/{id}/download",
    pattern: /^\/api\/v1\/files\/([^/]+)\/download\/?$/,
    scope: "files:read",
    summary: "파일함 파일 다운로드",
    operationId: "downloadFile",
    rewrite: (match) => `/api/me/files/${match[1]}/download`,
  }),
  route({
    method: "POST",
    path: "/api/v1/reports",
    pattern: /^\/api\/v1\/reports\/?$/,
    scope: "reports:write",
    summary: "보고서 생성 작업 제출",
    operationId: "createReport",
    idempotent: true,
    rewrite: () => "/api/generate",
  }),
  route({
    method: "POST",
    path: "/api/v1/pdf-translations/estimate",
    pattern: /^\/api\/v1\/pdf-translations\/estimate\/?$/,
    scope: "translations:read",
    summary: "PDF 통번역 방식, 비용과 시간 분석",
    operationId: "estimatePdfTranslation",
    rewrite: () => "/api/translate-pdf/estimate",
  }),
  route({
    method: "POST",
    path: "/api/v1/pdf-translations",
    pattern: /^\/api\/v1\/pdf-translations\/?$/,
    scope: "translations:write",
    summary: "PDF 통번역 작업 제출",
    operationId: "createPdfTranslation",
    idempotent: true,
    rewrite: () => "/api/translate-pdf",
  }),
  route({
    method: "POST",
    path: "/api/v1/conversions/docx-to-hwpx",
    pattern: /^\/api\/v1\/conversions\/docx-to-hwpx\/?$/,
    scope: "conversions:write",
    summary: "DOCX 문서를 HWPX로 변환",
    operationId: "convertDocxToHwpx",
    rewrite: () => "/api/convert-docx",
  }),
  route({ method: "POST", path: "/api/v1/documents/pdf/analyze", pattern: /^\/api\/v1\/documents\/pdf\/analyze\/?$/, scope: "documents:read", summary: "PDF 구조·텍스트층·스캔·수식 밀도 분석", operationId: "analyzePdf", rewrite: () => "/api/tools/pdf/analyze" }),
  route({ method: "POST", path: "/api/v1/documents/hwpx/equations", pattern: /^\/api\/v1\/documents\/hwpx\/equations\/?$/, scope: "documents:write", summary: "HWPX 안의 LaTeX와 수식 마커를 한글 수식 객체로 변환", operationId: "convertHwpxEquations", rewrite: () => "/api/tools/hwpx/equations" }),
  route({ method: "POST", path: "/api/v1/documents/images/ocr", pattern: /^\/api\/v1\/documents\/images\/ocr\/?$/, scope: "documents:write", summary: "이미지의 글·표·수식을 OCR로 추출", operationId: "ocrImage", rewrite: () => "/api/tools/images/ocr" }),
  route({ method: "POST", path: "/api/v1/documents/images/ocr/export", pattern: /^\/api\/v1\/documents\/images\/ocr\/export\/?$/, scope: "documents:write", summary: "OCR 편집 요소와 감지 그림 크롭을 DOCX, HWPX, HTML 또는 TXT로 내보내기", operationId: "exportOcrImage", rewrite: () => "/api/tools/images/ocr/export" }),
  route({ method: "POST", path: "/api/v1/tools/word-count", pattern: /^\/api\/v1\/tools\/word-count\/?$/, scope: "tools:read", summary: "공백 포함·제외 글자수, 단어, 줄, 문단과 UTF-8 바이트 계산", operationId: "countWords", rewrite: () => "/api/tools/word-count" }),
  route({ method: "POST", path: "/api/v1/tools/statistics", pattern: /^\/api\/v1\/tools\/statistics\/?$/, scope: "tools:read", summary: "기술통계와 사분위수 계산", operationId: "calculateStatistics", rewrite: () => "/api/tools/statistics" }),
  route({ method: "POST", path: "/api/v1/tools/regression", pattern: /^\/api\/v1\/tools\/regression\/?$/, scope: "tools:read", summary: "단순 선형회귀·상관계수·결정계수 계산", operationId: "calculateRegression", rewrite: () => "/api/tools/regression" }),
  route({ method: "GET", path: "/api/v1/tools/units", pattern: /^\/api\/v1\/tools\/units\/?$/, scope: "tools:read", summary: "지원 단위 범주와 단위 목록", operationId: "listUnits", rewrite: () => "/api/tools/units" }),
  route({ method: "POST", path: "/api/v1/tools/units/convert", pattern: /^\/api\/v1\/tools\/units\/convert\/?$/, scope: "tools:read", summary: "물리·과학 단위 변환", operationId: "convertUnit", rewrite: () => "/api/tools/units/convert" }),
  route({ method: "POST", path: "/api/v1/tools/equations/convert", pattern: /^\/api\/v1\/tools\/equations\/convert\/?$/, scope: "tools:read", summary: "LaTeX 수식을 읽기 쉬운 유니코드 표기로 변환", operationId: "convertEquationNotation", rewrite: () => "/api/tools/equations/convert" }),
  route({ method: "POST", path: "/api/v1/tools/tables/analyze", pattern: /^\/api\/v1\/tools\/tables\/analyze\/?$/, scope: "tools:read", summary: "CSV·Excel 시트와 숫자 열 기술통계 분석", operationId: "analyzeTable", rewrite: () => "/api/tools/tables/analyze" }),
  route({ method: "POST", path: "/api/v1/tools/graphs", pattern: /^\/api\/v1\/tools\/graphs\/?$/, scope: "tools:read", summary: "산점도·선·막대그래프를 PNG 또는 SVG로 렌더링", operationId: "renderGraph", rewrite: () => "/api/tools/graphs" }),
  route({ method: "GET", path: "/api/v1/webhooks", pattern: /^\/api\/v1\/webhooks\/?$/, scope: "webhooks:read", summary: "Webhook endpoint 목록", operationId: "listWebhooks", rewrite: () => "/api/integrations/webhooks" }),
  route({ method: "POST", path: "/api/v1/webhooks", pattern: /^\/api\/v1\/webhooks\/?$/, scope: "webhooks:write", summary: "서명 Webhook endpoint 생성", operationId: "createWebhook", rewrite: () => "/api/integrations/webhooks" }),
  route({ method: "DELETE", path: "/api/v1/webhooks/{id}", pattern: /^\/api\/v1\/webhooks\/([^/]+)\/?$/, scope: "webhooks:write", summary: "Webhook endpoint 삭제", operationId: "deleteWebhook", rewrite: (match) => `/api/integrations/webhooks/${match[1]}` }),
  route({ method: "GET", path: "/api/v1/webhook-deliveries", pattern: /^\/api\/v1\/webhook-deliveries\/?$/, scope: "webhooks:read", summary: "최근 Webhook 전송 결과", operationId: "listWebhookDeliveries", rewrite: () => "/api/integrations/webhook-deliveries" }),
  route({ method: "GET", path: "/api/v1/integrations", pattern: /^\/api\/v1\/integrations\/?$/, scope: "integrations:read", summary: "Dropbox·Google·Notion 연결 상태", operationId: "listIntegrations", rewrite: () => "/api/cloud/providers/status" }),
  route({ method: "GET", path: "/api/v1/integrations/byok", pattern: /^\/api\/v1\/integrations\/byok\/?$/, scope: "integrations:read", summary: "암호화 저장된 BYOK 제공자와 키 끝 4자리 상태", operationId: "getByokStatus", rewrite: () => "/api/me/api-keys" }),
  route({ method: "GET", path: "/api/v1/integrations/dropbox/link", pattern: /^\/api\/v1\/integrations\/dropbox\/link\/?$/, scope: "integrations:data", summary: "본인 Dropbox 파일의 열기 링크", operationId: "getDropboxLink", rewrite: () => "/api/cloud/dropbox/link" }),
  route({ method: "GET", path: "/api/v1/integrations/google-drive/files", pattern: /^\/api\/v1\/integrations\/google-drive\/files\/?$/, scope: "integrations:data", summary: "연결된 Google Drive 파일 목록", operationId: "listGoogleDriveFiles", rewrite: () => "/api/cloud/google/drive/files" }),
  route({ method: "POST", path: "/api/v1/integrations/google-drive/files", pattern: /^\/api\/v1\/integrations\/google-drive\/files\/?$/, scope: "integrations:write", summary: "사용자 지정 파일을 Google Drive에 업로드", operationId: "uploadGoogleDriveFile", rewrite: () => "/api/cloud/google/drive/upload" }),
  route({ method: "GET", path: "/api/v1/integrations/google-drive/folders", pattern: /^\/api\/v1\/integrations\/google-drive\/folders\/?$/, scope: "integrations:data", summary: "Quilo가 접근할 수 있는 Google Drive 폴더 목록", operationId: "listGoogleDriveFolders", rewrite: () => "/api/cloud/google/drive/folders" }),
  route({ method: "POST", path: "/api/v1/integrations/google-drive/folders", pattern: /^\/api\/v1\/integrations\/google-drive\/folders\/?$/, scope: "integrations:write", summary: "Google Drive 폴더 생성", operationId: "createGoogleDriveFolder", rewrite: () => "/api/cloud/google/drive/folders" }),
  route({ method: "GET", path: "/api/v1/integrations/google-drive/files/{id}/download", pattern: /^\/api\/v1\/integrations\/google-drive\/files\/([^/]+)\/download\/?$/, scope: "integrations:data", summary: "Google Drive 파일 다운로드 또는 Workspace 문서 내보내기", operationId: "downloadGoogleDriveFile", rewrite: (match) => `/api/cloud/google/drive/files/${match[1]}/download` }),
  route({ method: "POST", path: "/api/v1/integrations/google-drive/files/{id}/import", pattern: /^\/api\/v1\/integrations\/google-drive\/files\/([^/]+)\/import\/?$/, scope: "integrations:write", summary: "Google Drive 파일을 Quilo 24시간 파일함으로 가져오기", operationId: "importGoogleDriveFile", rewrite: (match) => `/api/cloud/google/drive/files/${match[1]}/import` }),
  route({ method: "POST", path: "/api/v1/integrations/google-drive/files/{id}/copy", pattern: /^\/api\/v1\/integrations\/google-drive\/files\/([^/]+)\/copy\/?$/, scope: "integrations:write", summary: "Google Drive 파일 사본 생성", operationId: "copyGoogleDriveFile", rewrite: (match) => `/api/cloud/google/drive/files/${match[1]}/copy` }),
  route({ method: "POST", path: "/api/v1/integrations/google-drive/reports/{id}", pattern: /^\/api\/v1\/integrations\/google-drive\/reports\/([^/]+)\/?$/, scope: "integrations:write", summary: "Quilo 생성 파일을 Drive에 저장하거나 Google Docs로 변환", operationId: "saveReportToGoogleDrive", rewrite: (match) => `/api/cloud/google/drive/reports/${match[1]}` }),
  route({ method: "GET", path: "/api/v1/integrations/google-drive/files/{id}/comments", pattern: /^\/api\/v1\/integrations\/google-drive\/files\/([^/]+)\/comments\/?$/, scope: "integrations:data", summary: "Google Drive 파일 댓글과 답글 목록", operationId: "listGoogleDriveComments", rewrite: (match) => `/api/cloud/google/drive/files/${match[1]}/comments` }),
  route({ method: "POST", path: "/api/v1/integrations/google-drive/files/{id}/comments", pattern: /^\/api\/v1\/integrations\/google-drive\/files\/([^/]+)\/comments\/?$/, scope: "integrations:write", summary: "Google Drive 파일 댓글 작성", operationId: "createGoogleDriveComment", rewrite: (match) => `/api/cloud/google/drive/files/${match[1]}/comments` }),
  route({ method: "POST", path: "/api/v1/integrations/google-docs", pattern: /^\/api\/v1\/integrations\/google-docs\/?$/, scope: "integrations:write", summary: "제목과 본문으로 Google Docs 문서 생성", operationId: "createGoogleDoc", rewrite: () => "/api/cloud/google/docs" }),
  route({ method: "POST", path: "/api/v1/integrations/google-docs/{id}/append", pattern: /^\/api\/v1\/integrations\/google-docs\/([^/]+)\/append\/?$/, scope: "integrations:write", summary: "기존 Google Docs 문서 끝에 본문 추가", operationId: "appendGoogleDoc", rewrite: (match) => `/api/cloud/google/docs/${match[1]}/append` }),
  route({ method: "POST", path: "/api/v1/integrations/{provider}/disconnect", pattern: /^\/api\/v1\/integrations\/(dropbox|google|notion)\/disconnect\/?$/, scope: "integrations:write", summary: "외부 서비스 연결 해제 및 가능한 경우 토큰 폐기", operationId: "disconnectIntegration", rewrite: (match) => `/api/cloud/${match[1]}/disconnect` }),
  route({ method: "POST", path: "/api/v1/integrations/notion/pages", pattern: /^\/api\/v1\/integrations\/notion\/pages\/?$/, scope: "integrations:write", summary: "제목과 Markdown으로 Notion 페이지 생성", operationId: "createNotionPage", rewrite: () => "/api/cloud/notion/pages" }),
  route({ method: "GET", path: "/api/v1/studios/vibe/config", pattern: /^\/api\/v1\/studios\/vibe\/config\/?$/, scope: "studios:read", summary: "Vibe Coding 모델과 비용 설정", operationId: "getVibeConfig", rewrite: () => "/api/vibe/config" }),
  route({ method: "POST", path: "/api/v1/studios/vibe/generate", pattern: /^\/api\/v1\/studios\/vibe\/generate\/?$/, scope: "studios:write", summary: "Vibe Coding 프로젝트 설계 생성", operationId: "generateVibeProject", rewrite: () => "/api/vibe/generate" }),
  route({ method: "POST", path: "/api/v1/studios/vibe/refine", pattern: /^\/api\/v1\/studios\/vibe\/refine\/?$/, scope: "studios:write", summary: "Vibe Coding 프로젝트 설계 수정", operationId: "refineVibeProject", rewrite: () => "/api/vibe/refine" }),
  route({ method: "POST", path: "/api/v1/studios/vibe/image", pattern: /^\/api\/v1\/studios\/vibe\/image\/?$/, scope: "studios:write", summary: "Vibe Coding 개념 이미지 생성", operationId: "generateVibeImage", rewrite: () => "/api/vibe/image" }),
  route({ method: "GET", path: "/api/v1/studios/artifacts/models", pattern: /^\/api\/v1\/studios\/artifacts\/models\/?$/, scope: "studios:read", summary: "창작 스튜디오 사용 가능 모델", operationId: "listArtifactModels", rewrite: () => "/api/artifacts/models" }),
  route({ method: "POST", path: "/api/v1/studios/artifacts/build", pattern: /^\/api\/v1\/studios\/artifacts\/build\/?$/, scope: "studios:write", summary: "웹·디자인 아티팩트 생성 또는 대화형 수정", operationId: "buildArtifact", rewrite: () => "/api/artifacts/build" }),
  route({ method: "GET", path: "/api/v1/studios/artifacts", pattern: /^\/api\/v1\/studios\/artifacts\/?$/, scope: "studios:read", summary: "본인의 저장된 아티팩트 목록", operationId: "listArtifacts", rewrite: () => "/api/artifacts" }),
  route({ method: "POST", path: "/api/v1/studios/artifacts", pattern: /^\/api\/v1\/studios\/artifacts\/?$/, scope: "studios:write", summary: "아티팩트 저장 및 게시 상태 설정", operationId: "saveArtifact", rewrite: () => "/api/artifacts" }),
  route({ method: "GET", path: "/api/v1/studios/artifacts/{id}", pattern: /^\/api\/v1\/studios\/artifacts\/([^/]+)\/?$/, scope: "studios:read", summary: "본인의 아티팩트 원본 읽기", operationId: "getArtifact", rewrite: (match) => `/api/artifacts/${match[1]}/raw` }),
  route({ method: "DELETE", path: "/api/v1/studios/artifacts/{id}", pattern: /^\/api\/v1\/studios\/artifacts\/([^/]+)\/?$/, scope: "studios:write", summary: "본인의 아티팩트 삭제", operationId: "deleteArtifact", rewrite: (match) => `/api/artifacts/${match[1]}` }),
  route({ method: "GET", path: "/api/v1/studios/code/models", pattern: /^\/api\/v1\/studios\/code\/models\/?$/, scope: "studios:read", summary: "Quilo Code 사용 가능 모델", operationId: "listCodeModels", rewrite: () => "/api/admin/code-assist/models" }),
  route({ method: "POST", path: "/api/v1/studios/code/assist", pattern: /^\/api\/v1\/studios\/code\/assist\/?$/, scope: "studios:write", summary: "현재 코드를 생성·수정·설명·디버그", operationId: "assistCode", rewrite: () => "/api/admin/code-assist" }),
  route({ method: "POST", path: "/api/v1/studios/code/projects", pattern: /^\/api\/v1\/studios\/code\/projects\/?$/, scope: "studios:write", summary: "멀티파일 프로젝트 생성·수정·디버그", operationId: "buildCodeProject", rewrite: () => "/api/artifacts/build" }),
  route({ method: "GET", path: "/api/v1/studios/physics/config", pattern: /^\/api\/v1\/studios\/physics\/config\/?$/, scope: "studios:read", summary: "물리 스튜디오 모델과 스타일 설정", operationId: "getPhysicsStudioConfig", rewrite: () => "/api/physics-studio/config" }),
  route({ method: "POST", path: "/api/v1/studios/physics/generate", pattern: /^\/api\/v1\/studios\/physics\/generate\/?$/, scope: "studios:write", summary: "심화 물리 문제와 풀이 생성", operationId: "generatePhysicsProblems", rewrite: () => "/api/physics-studio/generate" }),
  route({ method: "GET", path: "/api/v1/file-chat/access", pattern: /^\/api\/v1\/file-chat\/access\/?$/, scope: "chat:write", summary: "파일 챗봇 접근 가능 여부", operationId: "getFileChatAccess", rewrite: () => "/api/filechat/access" }),
  route({ method: "POST", path: "/api/v1/file-chat/messages", pattern: /^\/api\/v1\/file-chat\/messages\/?$/, scope: "chat:write", summary: "파일과 대화 맥락으로 스트리밍 응답 생성", operationId: "createFileChatMessage", rewrite: () => "/api/filechat" }),
  route({ method: "GET", path: "/api/v1/knowledge/lab", pattern: /^\/api\/v1\/knowledge\/lab\/?$/, scope: "knowledge:read", summary: "Quilo Lab 문서 목록", operationId: "listLabEntries", rewrite: () => "/api/lab/entries" }),
  route({ method: "GET", path: "/api/v1/knowledge/lab/{id}", pattern: /^\/api\/v1\/knowledge\/lab\/([^/]+)\/?$/, scope: "knowledge:read", summary: "Quilo Lab 문서 상세", operationId: "getLabEntry", rewrite: (match) => `/api/lab/entry/${match[1]}` }),
  route({ method: "GET", path: "/api/v1/community/posts", pattern: /^\/api\/v1\/community\/posts\/?$/, scope: "community:read", summary: "커뮤니티 글 목록", operationId: "listCommunityPosts", rewrite: () => "/api/community/posts" }),
  route({ method: "POST", path: "/api/v1/community/posts", pattern: /^\/api\/v1\/community\/posts\/?$/, scope: "community:write", summary: "커뮤니티 글 작성", operationId: "createCommunityPost", rewrite: () => "/api/community/posts" }),
  route({ method: "DELETE", path: "/api/v1/community/posts/{id}", pattern: /^\/api\/v1\/community\/posts\/([^/]+)\/?$/, scope: "community:write", summary: "본인 커뮤니티 글 삭제", operationId: "deleteCommunityPost", rewrite: (match) => `/api/community/posts/${match[1]}` }),
  route({ method: "POST", path: "/api/v1/community/posts/{id}/vote", pattern: /^\/api\/v1\/community\/posts\/([^/]+)\/vote\/?$/, scope: "community:write", summary: "커뮤니티 글 공감 전환", operationId: "voteCommunityPost", rewrite: (match) => `/api/community/posts/${match[1]}/vote` }),
  route({ method: "GET", path: "/api/v1/community/posts/{id}/comments", pattern: /^\/api\/v1\/community\/posts\/([^/]+)\/comments\/?$/, scope: "community:read", summary: "커뮤니티 댓글 목록", operationId: "listCommunityComments", rewrite: (match) => `/api/community/posts/${match[1]}/comments` }),
  route({ method: "POST", path: "/api/v1/community/posts/{id}/comments", pattern: /^\/api\/v1\/community\/posts\/([^/]+)\/comments\/?$/, scope: "community:write", summary: "커뮤니티 댓글 작성", operationId: "createCommunityComment", rewrite: (match) => `/api/community/posts/${match[1]}/comments` }),
  route({ method: "DELETE", path: "/api/v1/community/comments/{id}", pattern: /^\/api\/v1\/community\/comments\/([^/]+)\/?$/, scope: "community:write", summary: "본인 커뮤니티 댓글 삭제", operationId: "deleteCommunityComment", rewrite: (match) => `/api/community/comments/${match[1]}` }),
]);

function matchApiRoute(method, pathname) {
  for (const entry of API_V1_ROUTES) {
    if (entry.method !== method) continue;
    const match = String(pathname || "").match(entry.pattern);
    if (match) return { entry, match };
  }
  return null;
}

module.exports = { API_V1_ROUTES, matchApiRoute };
